const pad = (value) => String(value).padStart(2, '0');

export function computeNextScheduledTime({ index, lastScheduledTime, intervalMinutes = 10, now = new Date() }) {
    if (index < 3) return null;
    const stepMin = Number(intervalMinutes) || 10;
    const stepMs = stepMin * 60 * 1000;
    const TWENTY_MINUTES_IN_MS = 20 * 60 * 1000;

    const baseTime = index === 3 || !lastScheduledTime
        ? new Date(now.getTime() + TWENTY_MINUTES_IN_MS)
        : new Date(lastScheduledTime.getTime() + stepMs);

    return new Date(Math.ceil(baseTime.getTime() / stepMs) * stepMs);
}

export function computeAutoIncrementTime({ lastScheduledTime, intervalMinutes = 5, now = new Date() }) {
    const stepMin = Number(intervalMinutes) || 5;
    const stepMs = stepMin * 60 * 1000;
    const TWENTY_MINUTES_IN_MS = 20 * 60 * 1000;

    const baseTime = lastScheduledTime 
        ? new Date(lastScheduledTime.getTime() + stepMs)
        : new Date(now.getTime() + TWENTY_MINUTES_IN_MS);

    return new Date(Math.ceil(baseTime.getTime() / stepMs) * stepMs);
}

export function getScheduleHintText(meta = {}) {
    return [
        meta.placeholder,
        meta.ariaLabel,
        meta.label,
        meta.name,
        // meta.id, // Exclude ID to avoid matching autogenerated prefixes like :rc4:
        meta.value
    ]
        .filter(Boolean)
        .join(' ')
        .toLowerCase();
}

export function inferScheduleFieldKind(meta = {}) {
    const hint = getScheduleHintText(meta);
    if (!hint) return 'unknown';

    // Priority 1: explicitly mentions date/time words
    if (/\b(date|day|ngay)\b/.test(hint)) return 'date';
    if (/\b(time|hour|minute|gio)\b/.test(hint)) return 'time';

    // Priority 2: Looks like a Date pattern (YYYY-MM-DD, MM/DD/YYYY, etc.)
    if (/\d{4}[-.]\d{2}[-.]\d{2}/.test(hint) || /\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}/.test(hint)) {
        return 'date';
    }

    // Priority 3: Looks like a Time pattern (HH:mm)
    if (/\b(am|pm)\b/.test(hint) || /\b\d{1,2}:\d{2}\b/.test(hint)) {
        return 'time';
    }

    return 'unknown';
}


export function formatScheduleValue(date, kind, meta = {}) {
    if (!(date instanceof Date) || Number.isNaN(date.getTime())) {
        throw new Error('Invalid schedule date');
    }

    const hint = getScheduleHintText(meta);
    const year = date.getFullYear();
    const month = pad(date.getMonth() + 1);
    const day = pad(date.getDate());
    const hours = date.getHours();
    const minutes = pad(date.getMinutes());

    if (kind === 'time') {
        if (/\b(am|pm)\b/.test(hint)) {
            const hour12 = hours % 12 || 12;
            const meridiem = hours >= 12 ? 'PM' : 'AM';
            return `${hour12}:${minutes} ${meridiem}`;
        }

        return `${pad(hours)}:${minutes}`;
    }

    if (kind === 'date') {
        if (/dd\s*\/\s*mm/.test(hint)) return `${day}/${month}/${year}`;
        if (/mm\s*\/\s*dd/.test(hint) || hint.includes('/')) return `${month}/${day}/${year}`;
        if (hint.includes('.')) return `${year}.${month}.${day}`;
        return `${year}-${month}-${day}`;
    }

    throw new Error(`Unsupported schedule field kind: ${kind}`);
}

export function sortScheduleInputs(inputs = []) {
    return [...inputs].sort((a, b) => {
        if ((a.top ?? 0) !== (b.top ?? 0)) return (a.top ?? 0) - (b.top ?? 0);
        return (a.left ?? 0) - (b.left ?? 0);
    });
}

/**
 * Attempts to parse a date and time string from TikTok inputs back into a Date object.
 */
export function parseScheduleValue(dateStr, timeStr, now = new Date()) {
    if (!dateStr || !timeStr) return null;

    try {
        // Try to parse date (expected YYYY-MM-DD or DD/MM/YYYY or MM/DD/YYYY)
        let year, month, day;
        if (dateStr.includes('-')) {
            [year, month, day] = dateStr.split('-').map(Number);
        } else if (dateStr.includes('/')) {
            const parts = dateStr.split('/').map(Number);
            if (parts[0] > 12) { // Likely DD/MM/YYYY
                [day, month, year] = parts;
            } else { // Likely MM/DD/YYYY
                [month, day, year] = parts;
            }
        } else if (dateStr.includes('.')) {
            [year, month, day] = dateStr.split('.').map(Number);
        }

        // Try to parse time (expected HH:mm or HH:mm AM/PM)
        let hours, minutes;
        const timeMatch = timeStr.match(/(\d{1,2}):(\d{2})(?:\s*(AM|PM))?/i);
        if (!timeMatch) return null;

        hours = parseInt(timeMatch[1], 10);
        minutes = parseInt(timeMatch[2], 10);
        const meridiem = timeMatch[3];

        if (meridiem) {
            if (meridiem.toUpperCase() === 'PM' && hours < 12) hours += 12;
            if (meridiem.toUpperCase() === 'AM' && hours === 12) hours = 0;
        }

        // Build every field at once. Setting them one by one on top of today's
        // date overflows whenever today's day-of-month does not exist in the
        // target month -- on Aug 31, setMonth(September) lands on Oct 1, which
        // pushed the whole schedule a month out for runs just before midnight.
        const date = new Date(
            year || now.getFullYear(),
            month ? month - 1 : now.getMonth(),
            day || now.getDate(),
            hours,
            minutes,
            0,
            0
        );

        return date;
    } catch (e) {
        console.error('Error parsing schedule value:', e);
        return null;
    }
}

const MONTH_ABBREVIATIONS = [
    'jan', 'feb', 'mar', 'apr', 'may', 'jun',
    'jul', 'aug', 'sep', 'oct', 'nov', 'dec'
];

// TikTok chỉ cho lên lịch tối đa 10 ngày. Một nhãn không có năm mà đã lùi quá
// mốc này so với hiện tại thì gần như chắc chắn là lịch của năm sau (trường hợp
// đứng cuối tháng 12 nhìn sang đầu tháng 1).
const STALE_LABEL_GRACE_MS = 7 * 24 * 60 * 60 * 1000;

function readMonthAndDay(datePart) {
    const monthIndex = MONTH_ABBREVIATIONS.findIndex(
        (abbr) => new RegExp(`\\b${abbr}`, 'i').test(datePart)
    );

    if (monthIndex >= 0) {
        // "Jul 13", "13 Jul", "July 13" — ngày là số 1-2 chữ số duy nhất còn lại.
        const dayMatch = datePart.match(/\b(\d{1,2})\b/);
        if (!dayMatch) return null;
        return { month: monthIndex, day: Number(dayMatch[1]) };
    }

    // Dạng thuần số, năm đã được cắt bỏ trước đó: "07/13", "13/07", "-07-13".
    const numbers = datePart.split(/\D+/).filter(Boolean).map(Number);
    if (numbers.length < 2) return null;

    // Số đầu > 12 thì chỉ có thể là ngày (DD/MM), ngược lại theo mặc định
    // en-US của TikTok Studio là MM/DD.
    return numbers[0] > 12
        ? { month: numbers[1] - 1, day: numbers[0] }
        : { month: numbers[0] - 1, day: numbers[1] };
}

/**
 * Đọc nhãn trạng thái "đã lên lịch" trên TikTok Studio Content thành Date.
 *
 * Không dùng `new Date(text)` được: nhãn của TikTok thường bỏ năm khi lịch nằm
 * trong năm hiện tại, và V8 mặc định năm 2001 cho chuỗi kiểu "Jul 13, 3:30 PM",
 * đẩy toàn bộ lịch nối tiếp về quá khứ 25 năm.
 */
export function parseStudioScheduleLabel(text, now = new Date()) {
    if (!text || typeof text !== 'string') return null;

    const cleaned = text
        .replace(/scheduled\s*(for)?/i, ' ')
        .replace(/đã\s*lên\s*lịch/i, ' ')
        .replace(/\s+/g, ' ')
        .trim();
    if (!cleaned) return null;

    const timeMatch = cleaned.match(/(\d{1,2}):(\d{2})(?:\s*(AM|PM))?/i);
    if (!timeMatch) return null;

    let hours = parseInt(timeMatch[1], 10);
    const minutes = parseInt(timeMatch[2], 10);
    const meridiem = timeMatch[3];
    if (meridiem) {
        if (meridiem.toUpperCase() === 'PM' && hours < 12) hours += 12;
        if (meridiem.toUpperCase() === 'AM' && hours === 12) hours = 0;
    }
    if (hours > 23 || minutes > 59) return null;

    const datePart = `${cleaned.slice(0, timeMatch.index)} ${cleaned.slice(timeMatch.index + timeMatch[0].length)}`
        .replace(/,/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();

    const explicitYearMatch = datePart.match(/\b(20\d{2})\b/);
    const withoutYear = explicitYearMatch
        ? datePart.replace(explicitYearMatch[0], ' ').replace(/\s+/g, ' ').trim()
        : datePart;

    const monthDay = readMonthAndDay(withoutYear);
    if (!monthDay) return null;
    const { month, day } = monthDay;
    if (!(month >= 0 && month <= 11) || !(day >= 1 && day <= 31)) return null;

    const build = (year) => {
        const date = new Date(year, month, day, hours, minutes, 0, 0);
        // Ngày không tồn tại (31/02, 29/02 năm thường) bị Date tự tràn sang
        // tháng sau — loại bỏ thay vì trả về mốc sai.
        if (date.getMonth() !== month || date.getDate() !== day) return null;
        return date;
    };

    if (explicitYearMatch) return build(Number(explicitYearMatch[1]));

    const sameYear = build(now.getFullYear());
    if (sameYear && sameYear.getTime() >= now.getTime() - STALE_LABEL_GRACE_MS) {
        return sameYear;
    }
    return build(now.getFullYear() + 1) || sameYear;
}
